### ISSUE TITLE
Replace PNG images with svg images for Clumit theme

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/frontary#129]
### Background
- Thanks to https://github.com/aicers/frontary/pull/109, now we can use the `Svg` component.

### Detail
- We will change the PNG image files used in Clumit theme (“pumpkin-dark” or "pumpkin-light"), to the `Svg` component.
  - I think changing all PNG files at once might be huge, so we can consider breaking down this issue to smaller parts.
- We can ask the design team to create images in SVG format.

**Comment by sehkone** [comment]
The `Svg` component of Frontary was initially introduced because Safari lacked sharpness when rendering SVG files. However, the recent version of Safari appears to have resolved this issue, even though there hasn't been an official announcement. Therefore, I suggest replacing only a few PNG images with SVG files and monitoring the situation to see if the problem is completely resolved.

**Comment by sehkone** [comment]
@dayeon5470 @jinjoolee07 @div-seungha, and @sophie-cluml,

Under the new version of Safari in the latest Mac OS, I feel there are no problems using SVG files. Therefore, we need to replace all PNG images with SVG ones. Doing this for the pumpkin design is a high priority, whereas this is not the case for the others.
